print("Percobaan -1")
print("Bukan Yang Ini")
print("Percobaan 0")
print("Ini Lagi Uji Coba")
print("Percobaan 1")
print("Tapi Ini Dari Local")
print("Percobaan 2")
print("Bukan Yang Ini Juga")
print("Percobaan 3")
print("Tapi Yang Ini")
print("Percobaan 4")
print("ININININININI")
print("ININININININI")
print("ININININININI")
print("ININININININI")
print("ININININININI")
